- rest:
    post:
    - id: "order"
      path: "/order"
      consumes: "application/json"
      produces: "application/json"
      param:
      - name: "body"
        required: true
        type: "body"
      to: "direct:order"
